"""Sysrepo planes, schema indexes, caches, and commit notifications.

Backend abstraction for the three emulated planes (IHUB, SHELF, LT[1-4]).
Each Plane instance owns:
- sysrepo repository path and SHM prefix (env vars for sysrepocfg).
- Merged schema index (generated by yanglint at build + curated fallback).
- Caches: running signature (cheap SHM mtime/size hash), XML exports,
  parsed XML roots, list instance keys.
- CommitWatcher thread polling running signature and emitting ConfD-style
  async commit notifications to stdout.

Schema index merging
--------------------
The generated index from yanglint (cli_index_<plane>.json.gz) is incomplete
for schema-mount subtrees (onus/onu, interfaces/interface with xpon
augments). yanglint fails mid-way and emits partial stdout, leaving those
lists as containers without keys. To make CLI navigation *always* work, we
merge a curated fallback tree *under* the generated one: generated wins where
present; curated fills gaps (list keys, loose flags, module names). See
_merge_index() and fallback_tree().

Cache strategy
--------------
- Running signature: cached for SIG_CACHE_SECONDS (default 0.15s) to avoid
  re-scanning /dev/shm on every TAB completion.
- XML exports: LRU cache keyed by (datastore, module, xpath) + signature.
- List instances: cached per (module, path_names, key_names, ancestor_keys,
  prefix_values) + signature; powers TAB completion for list keys.
- All caches invalidate on successful commit (apply_edit -> invalidate_cache).

Permission model
----------------
sysrepocfg on running datastore requires root (files in /dev/shm are 0600
owned by root from netopeer2/oper_push). The emulator runs as login user
(admin). Plane.run() detects non-root and prepends `sudo -n` with preserved
SYSREPO_* env vars (`-E`). If sudo absent or already root, runs directly.
This mirrors the real OLT where a single privileged backend serves both CLI
and NETCONF sessions.
"""

import gzip
import json
import os
import re
import subprocess
import sys
import threading
import time
import xml.etree.ElementTree as ET

from .common import (
    COMMIT_POLL_SECONDS, IDX_PATH, PLANES, SIG_CACHE_SECONDS,
    XML_CACHE_MAX, _SUDO,
)
from .rendering import clone_roots, xml_child_text, xml_path_elements, xml_roots

CONFD_PREAMBLE = """\
confdConfig encryptedStrings externalKeys command /isam/scripts/get_keys.sh
confdConfig parserLimits maxAttributeValueLength 4096    ! 16384
confdConfig parserLimits maxDataLength 8192    ! unbounded
confdConfig aaa defaultGroup defaultGroup
confdConfig aaa authOrder "externalAuthentication localAuthentication"
confdConfig aaa externalAuthentication enabled
confdConfig aaa externalAuthentication executable /etc/confd/radius_external_auth_start.sh
confdConfig aaa externalAuthentication includeExtra true    ! false
confdConfig aaa authenticationCallback enabled
confdConfig ssh idleConnectionTimeout 1s    ! 10m
confdConfig ssh algorithms serverHostKey ssh-rsa,ssh-dss    ! ssh-rsa,ssh-dss
confdConfig ssh algorithms kex diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group-exchange-sha256    ! diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group-exchange-sha256
confdConfig ssh algorithms mac hmac-sha2-256,hmac-sha2-512    ! hmac-sha2-256,hmac-sha2-512
confdConfig ssh algorithms encryption aes128-ctr,aes192-ctr,aes256-ctr    ! aes128-ctr,aes192-ctr,aes256-ctr
confdConfig ssh clientAliveInterval 300s    ! infinity
confdConfig ssh clientAliveCountMax 3    ! 3
confdConfig netconf transport ssh enabled
confdConfig netconf transport ssh ip 0.0.0.0    ! 0.0.0.0
confdConfig netconf transport ssh port {port}    ! 830
confdConfig netconf transport ssh extraIpPorts [ [0::0]:{port} ]
confdConfig netconf transport tcp enabled
confdConfig netconf transport tcp ip 127.0.0.1    ! 127.0.0.1
confdConfig netconf transport tcp port 2023    ! 2023
confdConfig netconf transport tcp extraIpPorts [ [0::1]:2023 ]
confdConfig netconf extendedSessions true    ! false
confdConfig netconf idleTimeout 0s    ! 0s
confdConfig netconf writeTimeout 30m    ! 0s
confdConfig notifications eventStreams stream NETCONF
 description   "RFC 5277 Default Notifications Stream"
 replaySupport true
 builtinReplayStore enabled
 builtinReplayStore dir /run/confd/log
 builtinReplayStore maxSize S1M
 builtinReplayStore maxFiles 10
!
confdConfig logs confdLog disabled
confdConfig logs confdLog file enabled
confdConfig logs confdLog file name /var/confd/log/confd.log
confdConfig logs confdLog syslog disabled
confdConfig logs developerLog enabled
confdConfig logs developerLog file enabled
confdConfig logs developerLog file name /isam/logs/confd_internal/devel.log
confdConfig logs developerLog syslog disabled
confdConfig logs developerLogLevel info    ! info
confdConfig logs auditLog enabled
confdConfig logs auditLog file enabled
confdConfig logs auditLog file name /var/confd/log/audit.log
confdConfig logs auditLog syslog disabled
confdConfig logs netconfLog enabled
confdConfig logs netconfLog file enabled"""

# --------------------------------------------------------------------------
# Curated fallback used when the generated schema index is missing or partial.
# --------------------------------------------------------------------------
def _loose(mod):
    return {"k": "c", "m": mod, "c": {}, "loose": 1}


FALLBACK_NS = {
    "ietf-interfaces": "urn:ietf:params:xml:ns:yang:ietf-interfaces",
    "ietf-hardware": "urn:ietf:params:xml:ns:yang:ietf-hardware",
    "ietf-system": "urn:ietf:params:xml:ns:yang:ietf-system",
    # yanglint uses the augment's YANG prefix in its compiled tree instead of
    # the full module name in some paths. Keep both forms so augmented leaves
    # are never serialized without their namespace.
    "bbf-hw-ext": "urn:bbf:yang:bbf-hardware-extension",
    "bbf-hardware-extension": "urn:bbf:yang:bbf-hardware-extension",
    "bbf-qos-tm": "urn:bbf:yang:bbf-qos-traffic-mngt",
    "nokia-mcast-cac": ("uri:http://www.nokia.com/Fixed-Networks/BBA/yang/"
                         "nokia-multicast-cac"),
    "bbf-xpon": "urn:bbf:yang:bbf-xpon",
    "bbf-xpongemtcont": "urn:bbf:yang:bbf-xpongemtcont",
    "bbf-qos-traffic-mngt": "urn:bbf:yang:bbf-qos-traffic-mngt",
    "bbf-fiber-onu-emulated-mount":
        "urn:bbf:params:xml:ns:yang:bbf-fiber-onu-emulated-mount",
    "nokia-onus-from-template":
        "http://www.nokia.com/Fixed-Networks/BBA/yang/onus-from-template",
    "nokia-conf": "urn:nokia.com:sros:ns:yang:sr:conf",
}


def schema_prefix_aliases(yangdir, namespaces):
    """Map each module's declared YANG prefix to its known namespace."""
    aliases = {}
    try:
        names = os.listdir(yangdir)
    except OSError:
        return aliases
    for filename in names:
        if not filename.endswith(".yang"):
            continue
        try:
            with open(os.path.join(yangdir, filename), errors="replace") as src:
                body = src.read(4096)
        except OSError:
            continue
        module = re.search(r'^\s*module\s+"?([\w.-]+)"?\s*\{', body, re.M)
        prefix = re.search(r'^\s*prefix\s+"?([\w.-]+)"?\s*;', body, re.M)
        if not (module and prefix):
            continue
        namespace = namespaces.get(module.group(1))
        if namespace:
            aliases[prefix.group(1)] = namespace
    return aliases


def _merge_index(curated, gen):
    """Merge the curated tree underneath the generated schema index.

    Generated nodes take precedence. Curated-only nodes are added, and curated
    list metadata fills in generated nodes that are missing their keys. Child
    trees are merged recursively. This repairs mounted paths such as
    ``onus/onu`` and ``interfaces/interface`` when yanglint leaves them as
    empty containers.
    """
    out = dict(gen)
    for name, cnode in curated.items():
        gnode = out.get(name)
        if gnode is None:
            out[name] = cnode
            continue
        merged = dict(gnode)
        # Restore list metadata when the generated node does not have it.
        if cnode.get("k") == "l" and (gnode.get("k") != "l"
                                      or not gnode.get("keys")):
            merged["k"] = "l"
            merged["keys"] = cnode.get("keys", [])
            if "m" not in merged and "m" in cnode:
                merged["m"] = cnode["m"]
        # Loose nodes allow navigation below incomplete mounted schemas.
        if cnode.get("loose") and not merged.get("loose"):
            merged["loose"] = 1
        if "m" not in merged and "m" in cnode:
            merged["m"] = cnode["m"]
        # Merge children recursively.
        gc = gnode.get("c") or {}
        cc = cnode.get("c") or {}
        if gc or cc:
            merged["c"] = _merge_index(cc, gc)
        out[name] = merged
    return out


def fallback_tree(plane):
    if plane == "ihub":
        return {"configure": _loose("nokia-conf")}
    leaf = lambda m, t="string": {"k": "f", "m": m, "t": t}
    t = {
        "system": {"k": "c", "m": "ietf-system",
                   "c": {"hostname": leaf("ietf-system")}},
        "hardware": {"k": "c", "m": "ietf-hardware", "c": {
            "component": {"k": "l", "m": "ietf-hardware", "keys": ["name"],
                          "loose": 1, "c": {
                "class": leaf("ietf-hardware", "identityref"),
                "parent": leaf("ietf-hardware"),
                "parent-rel-pos": leaf("ietf-hardware", "int32"),
                "mfg-name": leaf("ietf-hardware"),
                "model-name": leaf("bbf-hardware-extension"),
                "serial-num": leaf("ietf-hardware"),
            }}}},
    }
    if plane == "lt":
        t["onus"] = {"k": "c", "m": "bbf-fiber-onu-emulated-mount", "c": {
            "onu": {"k": "l", "m": "bbf-fiber-onu-emulated-mount",
                    "keys": ["name"], "loose": 1, "c": {
                "usage": leaf("bbf-fiber-onu-emulated-mount"),
                # Mounted root for classifiers, policies, interfaces,
                # xpongemtcont, and hardware. Loose means freely navigable.
                "root": _loose("bbf-fiber-onu-emulated-mount"),
                # Parameters recorded when an ONU is created from a template.
                "template-parameters": {
                    "k": "c", "m": "nokia-onus-from-template", "c": {
                        "template-ref": leaf("nokia-onus-from-template"),
                        "tconts": {"k": "c", "m": "nokia-onus-from-template",
                                   "c": {"tcont": {
                                       "k": "l",
                                       "m": "nokia-onus-from-template",
                                       "keys": ["template-ref"], "loose": 1,
                                       "c": {"id": leaf(
                                           "nokia-onus-from-template",
                                           "uint32")}}}},
                        "gemports": {"k": "c", "m": "nokia-onus-from-template",
                                     "c": {"gemport": {
                                         "k": "l",
                                         "m": "nokia-onus-from-template",
                                         "keys": ["template-ref"], "loose": 1,
                                         "c": {"id": leaf(
                                             "nokia-onus-from-template",
                                             "uint32")}}}},
                        "interfaces": {
                            "k": "c", "m": "nokia-onus-from-template", "c": {
                                "interface": {
                                    "k": "l",
                                    "m": "nokia-onus-from-template",
                                    "keys": ["template-ref"], "loose": 1,
                                    "c": {}}}},
                        "hardware-config": {
                            "k": "c", "m": "nokia-onus-from-template", "c": {
                                "hardware": {
                                    "k": "l",
                                    "m": "nokia-onus-from-template",
                                    "keys": ["template-ref"], "loose": 1,
                                    "c": {}}}},
                    }},
            }}}}
        t["interfaces"] = {"k": "c", "m": "ietf-interfaces", "c": {
            "interface": {"k": "l", "m": "ietf-interfaces", "keys": ["name"],
                          "loose": 1, "c": {
                "type": leaf("ietf-interfaces", "identityref"),
                "enabled": leaf("ietf-interfaces", "boolean"),
                "description": leaf("ietf-interfaces"),
                "channel-group": _loose("bbf-xpon"),
                "channel-partition": _loose("bbf-xpon"),
                "channel-pair": _loose("bbf-xpon"),
                "channel-termination": _loose("bbf-xpon"),
                "v-ani": _loose("bbf-xpon"),
                "tm-root": _loose("bbf-qos-traffic-mngt"),
                "port-layer-if": {"k": "F", "m": "bbf-xpon"},
            }}}}
        t["xpongemtcont"] = _loose("bbf-xpongemtcont")
        t["tm-profiles"] = _loose("bbf-qos-traffic-mngt")
    return t


# --------------------------------------------------------------------------
# Sysrepo backend.
# --------------------------------------------------------------------------
class Plane:
    def __init__(self, name):
        self.name = name
        m = re.fullmatch(r"lt([2-4])", name)
        if m and name not in PLANES:
            # Runtime LT clones share the LT schema index but use their own
            # repository, shared-memory prefix, and NETCONF port.
            n = int(m.group(1))
            self.repo, self.shm, self.port = ("/repo/lt%d" % n,
                                              "lt%d_" % n, 832 + n)
            self.idx_name = "lt"
        else:
            self.repo, self.shm, self.port = PLANES[name]
            self.idx_name = name
        self.env = dict(os.environ, SYSREPO_REPOSITORY_PATH=self.repo,
                        SYSREPO_SHM_PREFIX=self.shm)
        self._idx = self._ns = self._desc = None
        self._suppress_commit_notice_until = 0.0
        self._inst_cache = {}   # (module, path, keys, filters) -> (sig, rows)
        self._xml_cache = {}     # (ds, module, xpath) -> (sig, xml)
        self._roots_cache = {}   # (ds, module, xpath) -> (sig, [ET roots])
        self._sig_cache = None
        self._sig_cache_at = 0.0

    def _load(self):
        if self._idx is not None:
            return
        gen = None
        try:
            with gzip.open(IDX_PATH % self.idx_name, "rb") as f:
                data = json.loads(f.read())
            gen = data["tree"]
            self._ns = dict(FALLBACK_NS, **data.get("ns", {}))
            self._desc = data.get("desc", {})
        except Exception:
            self._ns = dict(FALLBACK_NS)
            self._desc = {}
        # Older base images indexed module names but not the prefixes emitted
        # by ``yanglint -f tree`` for augments. Recover every alias directly
        # from the installed schemas so this overlay fixes more than a static
        # list of known modules.
        self._ns.update(schema_prefix_aliases(
            os.path.join(self.repo, "yang"), self._ns))
        # Mounted Lightspan schemas can make yanglint stop after emitting a
        # partial index. Merge in the curated tree so paths such as
        # ``onus onu <X>`` and ``interfaces interface <Y>`` retain list keys.
        curated = fallback_tree(self.idx_name)
        if gen is None:
            self._idx = curated
        else:
            self._idx = _merge_index(curated, gen)

    @property
    def index(self):
        self._load()
        return self._idx

    def desc(self, name):
        self._load()
        return self._desc.get(name, "")

    def ns_of(self, module):
        self._load()
        return self._ns.get(module, "")

    def root_node(self, name):
        self._load()
        return self._idx.get(name)

    def invalidate_cache(self):
        self._sig_cache = None
        self._sig_cache_at = 0.0
        self._xml_cache.clear()
        self._roots_cache.clear()
        self._inst_cache.clear()

    def _cache_put(self, cache, key, value):
        cache[key] = value
        while len(cache) > XML_CACHE_MAX:
            cache.pop(next(iter(cache)))

    def running_signature(self):
        """Return a cheap signature for the live running datastores."""
        now = time.monotonic()
        if (self._sig_cache is not None
                and now - self._sig_cache_at < SIG_CACHE_SECONDS):
            return self._sig_cache
        prefix = self.shm + "_"
        sig = []
        try:
            for fn in os.listdir("/dev/shm"):
                if not (fn.startswith(prefix) and fn.endswith(".running")):
                    continue
                path = os.path.join("/dev/shm", fn)
                try:
                    st = os.stat(path)
                except OSError:
                    continue
                sig.append((fn, st.st_size, st.st_mtime_ns))
        except OSError:
            return ()
        self._sig_cache = tuple(sorted(sig))
        self._sig_cache_at = now
        return self._sig_cache

    def suppress_commit_notice(self, seconds=5.0):
        self._suppress_commit_notice_until = time.time() + seconds

    def commit_notice_suppressed(self):
        return time.time() < self._suppress_commit_notice_until

    def run(self, args):
        # netopeer2 and oper_push create 0600 datastore files as root. The eCLI
        # normally runs as the admin login user, so sysrepo operations need
        # non-interactive sudo. Already-root processes, and minimal images
        # without sudo, execute directly. Explicit SYSREPO_* values keep the
        # operation on the requested plane.
        if os.geteuid() != 0 and _SUDO:
            args = [_SUDO, "-n", "/usr/bin/env",
                    "SYSREPO_REPOSITORY_PATH=" + self.repo,
                    "SYSREPO_SHM_PREFIX=" + self.shm] + list(args)
        return subprocess.run(args, env=self.env, capture_output=True,
                              text=True)

    def export_xml(self, ds="running", module=None, xpath=None):
        ck = (ds, module, xpath)
        sig = self.running_signature() if ds == "running" else None
        if ds == "running":
            cached = self._xml_cache.get(ck)
            if cached is not None and cached[0] == sig:
                return cached[1]
        cmd = ["sysrepocfg", "-X", "-d", ds, "-f", "xml"]
        if module:
            cmd += ["-m", module]
        if xpath:
            cmd += ["-x", xpath]
        r = self.run(cmd)
        if r.returncode != 0:
            return None
        if ds == "running":
            self._cache_put(self._xml_cache, ck, (sig, r.stdout))
        return r.stdout

    def export_xml_roots(self, ds="running", module=None, xpath=None,
                         clone=False):
        ck = (ds, module, xpath)
        sig = self.running_signature() if ds == "running" else None
        if ds == "running":
            cached = self._roots_cache.get(ck)
            if cached is not None and cached[0] == sig:
                roots = cached[1]
                return clone_roots(roots) if clone else roots
        roots = xml_roots(self.export_xml(ds, module, xpath))
        if ds == "running":
            self._cache_put(self._roots_cache, ck, (sig, roots))
        return clone_roots(roots) if clone else roots

    def list_instances(self, module, top_name, path_names, key_names,
                       path_keys=None, prefix_values=None):
        """Return keys for list instances that exist in running.

        ``path_names`` runs from the root to the target list, while
        ``key_names`` describes that list's keys. ``path_keys`` filters any
        ancestor lists already resolved. ``prefix_values`` contains keys
        already typed for a multi-key list. Results feed TAB/``?`` completion
        and are cached against the running datastore signature.
        """
        if not module or not path_names or not key_names:
            return []
        path_keys = path_keys or {}
        prefix_values = list(prefix_values or [])
        if len(prefix_values) >= len(key_names):
            return []
        top_node = self.root_node(top_name)
        export_module = (top_node or {}).get("m") or module
        sig = self.running_signature()
        key_filters = tuple(
            (pos, tuple(sorted((kv or {}).items())))
            for pos, kv in sorted(path_keys.items())
        )
        ck = (export_module, tuple(path_names), tuple(key_names),
              key_filters, tuple(prefix_values))
        cached = self._inst_cache.get(ck)
        if cached is not None and cached[0] == sig:
            return cached[1]
        # Export the top module and walk by local names. Mounted and augmented
        # subtrees can change XML namespaces, so an unprefixed absolute XPath
        # is not portable across sysrepo versions.
        out = []
        roots = self.export_xml_roots("running", export_module)
        if roots:
            want_key = key_names[len(prefix_values)]
            for el in xml_path_elements(roots, path_names, path_keys):
                ok = True
                for key, expected in zip(key_names, prefix_values):
                    if xml_child_text(el, key) != expected:
                        ok = False
                        break
                if not ok:
                    continue
                val = xml_child_text(el, want_key)
                if val:
                    out.append((val, ""))
        out = sorted(set(out))
        self._inst_cache[ck] = (sig, out)
        return out

    def apply_edit(self, xml_str, module, ds):
        path = "/tmp/ecli_%s_%d.xml" % (self.name, os.getpid())
        with open(path, "w") as f:
            f.write(xml_str)
        try:
            r = self.run(["sysrepocfg", "--edit=" + path, "-d", ds,
                          "-m", module, "-v2"])
            if r.returncode == 0:
                self.invalidate_cache()
            return r
        finally:
            try:
                os.unlink(path)
            except OSError:
                pass


class CommitWatcher:
    """Emit the ConfD-style notification used after external NETCONF commits."""
    def __init__(self, plane, user):
        self.plane = plane
        self.user = user
        self._stop = threading.Event()
        self._thread = None
        self._last = None

    def start(self):
        if self._thread is not None:
            return
        self._last = self.plane.running_signature()
        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()

    def stop(self):
        self._stop.set()

    def _run(self):
        while not self._stop.wait(COMMIT_POLL_SECONDS):
            sig = self.plane.running_signature()
            if sig == self._last:
                continue
            self._last = sig
            if self.plane.commit_notice_suppressed():
                continue
            ts = time.strftime("%Y-%m-%d %H:%M:%S")
            sys.stdout.write(
                "\nSystem message at %s...\n"
                "Commit performed by %s via ssh using netconf.\n" %
                (ts, self.user)
            )
            sys.stdout.flush()
